WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import path,re_path
from catalog import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
]

WebBooks/catalog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Genre(models.Model):
    name=models.CharField(max_length=200,help_text="Введите жанр книги", verbose_name="Жанр книги")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20, help_text="Введите язык книги", verbose_name="Язык книги")

    def __str__(self):
        return self.name

class Author(models.Model):
    firs_name = models.CharField(max_length=100, help_text="Введите имя автора", verbose_name="Имя автора")
    last_name = models.CharField(max_length=100, help_text="Введите фамилию автора", verbose_name="Фамилия автора")
    date_of_birth = models.DateField( help_text="Введите дату рождения", verbose_name="Дата рождения", null=True,blank=True)
    date_of_death = models.DateField(help_text="Введите дату смерти", verbose_name="Дата смерти", null=True,
                                     blank=True)

    def __str__(self):
        return self.last_name

class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Введите название книги",
                             verbose_name="Название книги")
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE,
                              help_text=" Выберите жанр для книги",
                              verbose_name="Жанр книги", null=True)
    language = models.ForeignKey('Language',
                                 on_delete=models.CASCADE,
                                 help_text="Выберите язык книги",
                                 verbose_name="Язык книги", null=True)
    author = models.ManyToManyField('Author',
                                    help_text="Выберите автора книги",
                                    verbose_name="Автор книги")
    summary = models.TextField(max_length=1000,
                               help_text="Введите краткое описание книги",
                               verbose_name="Аннотация книги")
    isbn = models.CharField(max_length=13,
                            help_text="Должно содержать 13 символов",
                            verbose_name="ISBN книги")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Возвращает url-адрес для доступа к определенному экземпляру книги.
        return reverse('book-detail', args=[str(self.id)])


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите статус экземпляра книги",
                            verbose_name="Статус экземпляра книги")

    def __str__(self):
        return self.name

class BookInstance(models.Model):
    objects = None
    book = models.ForeignKey('Book', on_delete=models.CASCADE,
                             null=True)
    inv_nom = models.CharField(max_length=20, null=True,
                               help_text="Введите инвентарный номер экземпляра",
                               verbose_name="Инвентарный номер")
    imprint = models.CharField(max_length=200,
                               help_text="Введите издательство и год выпуска",
                               verbose_name="Издательство")
    status = models.ForeignKey('Status', on_delete=models.CASCADE,
                               null=True,
                               help_text='Изменить состояние экземпляра',
                               verbose_name="Статус экземпляра книги")
    due_back = models.DateField(null=True, blank=True,
                                help_text="Введите конец срока статуса",
                                verbose_name="Дата окончания статуса")

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

WebBooks/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.views import generic

# Create your views here.

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.all().filter(status__exact=2).count()
    num_authors = Author.objects.all().count()

    return render(request,"index.html",context={
    'num_books':num_books,
    'num_instances':num_instances,
    'num_instances_available':num_instances_available,
    'num_authors':num_authors}
                  )

class BookListView(generic.ListView):
    model = Book
    paginate_by = 2

class BookDetailView(generic.DetailView):
    model = Book

WebBooks/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Мир книг</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="../static/boots/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="../static/boots/js/bootstrap.min.js"></script>

  <!-- Добавление статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block head %}
      <img src="{% static 'images/logotip.jpg' %}" style="width:100px; height:100px;"  align="absmiddle">
      <font size=7, color="blue">Сайт "Мир книг"</font>
  {% endblock %}
</head>

<body>
  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Главная страница</a></li>
          <li><a href="{% url 'books' %}">Все книг</a></li>
          <li><a href="">Все авторы</a></li>
      </ul>
      {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
          {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{page_obj.previous_page_number }}
                           ">Предыдущая</a>
              {% endif %}
              <span class="page-current">
                  Страница {{ page_obj.number }} из
                       {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{page_obj.next_page_number }}
                           ">Следующая</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      {% block footer %}
         {% block copyright %}
       <p>Copyright ООО "Люди и книги", 2020. Все права защищены</p>
         {% endblock %}
      {% endblock %}

      </div>
    </div>
  </div>
</body>
</html>


WebBooks/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Название книги: {{ book.title }}</h1>

  <p><strong>Жанр:</strong> {{ book.genre }}</p>
  <p><strong>Аннотация:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Язык:</strong> {{ book.language }}</p>
     {% for author in book.author.all %}
        <p><strong>Автор:</strong>
           <a href="">{{ author.first_name }}
                      {{author.last_name}}</a></p>
     {% endfor %}

<div style="margin-left:20px;margin-top:20px">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
       <hr><p class="{% if copy.status == 1 %} text-success{% elif copy.status == 2 %} text-danger{% else %} text-warning{% endif %}"> {{ copy.get_status_display }}</p>
       <p><strong>Издательство:</strong> {{copy.imprint}}</p>
       <p class="text-muted"><strong>Инвентарный номер:</strong> {{copy.id}}</p>
       <p><strong>Статус экземпляра книги в БД:</strong> {{copy.status}}</p>
    {% endfor %}
  </div>
{% endblock %}   .
<p><strong>Автор:</strong> <a href="">{{ author.first_name }}  {{author.last_name}}</a></p>

WebBooks/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг в БД</h1>
    {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}"> {{ book.title }}</a>
                 ({{book.genre}})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>В базе данных нет книг</p>
    {% endif %}
{% endblock %}

WebBooks/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Главная страница</h1>

  <p>Добро пожаловать в <em>Мир книг</em>, Это очень простой
    веб-сайт, написанный на  Django. Разработан на Python
    в качестве учебного примера с использованием PyCharm.</p>

<h2>Динамический контент</h2>

  <p>База данных сайта Мир книг содержит следующее
     количество записей :</p>
  <ul>
    <li><strong>Количество книг:</strong> {{ num_books }}</li>
    <li><strong>Количество экземпляров книг:
        </strong> {{ num_instances }}</li>
    <li><strong>Количество экземпляров книг в заказе:
        </strong> {{ num_instances_available }}</li>
    <li><strong>Количество авторов книг:
        </strong> {{ num_authors }}</li>
  </ul>
{% endblock %}